	include cpyright.def

;*****************************************************
;*
;*	RTM - MP/M-86 or CCP/M Real Time Monitor
;*
;*****************************************************
	eject ! include system.def
	eject ! include modfunc.def
	eject ! include modtab.def
	eject ! include xioscb.def
	eject ! include flg.def
	eject ! include mem.def
	eject ! include mpb.def
	eject ! include pd.def
	eject ! include err.def
	eject ! include qd.def
	eject ! include sync.def
	eject ! include cmdh.def
	eject ! include apb.def
	eject ! include vccb.def
        eject ! include uda.def
        eject ! include s8087.lib
	eject ! include rtmif.rtm
	eject ! include sysent.rtm
	eject ! include proc.rtm
	eject ! include dsptch.rtm
	eject ! include flag.rtm
	eject ! include que1.rtm
	eject ! include que2.rtm
	eject ! include findpd.rtm
	eject ! include abort.rtm
	eject ! include patch.cod
	eject ! include vec.fmt
	eject ! include uda.fmt
	eject ! include sysdat.dat
	eject ! include data.bdo
	eject ! include xiosdat.fmt			;SUP 5 - DH - 14APR82
	eject ! end
